on:
  push:
    # branches:
    # - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read

name: main
jobs:
  sign_test:
    name: 'Sign test'
    runs-on: windows-latest
    environment: release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: Create msixbundle with Advanced Installer
    #   uses: caphyon/advinst-github-action@main
    #   with:
    #     advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
    #     advinst-enable-automation: 'true'
    #     aip-path: ImageMagick.Q16-HDRI.aip
    #     aip-build-name: Build_MSIX

    - name: Sign binaries
      uses: azure/trusted-signing-action@v0.3.16
      with:
        endpoint: https://eus.codesigning.azure.net/
        code-signing-account-name: ImageMagick
        certificate-profile-name: ImageMagick
        files-folder: 'x64'
        files-folder-filter: dll,exe
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256
